name: FTP Deploy

on:
  push:
    branches:
      - primary

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore SchoolManagement/SchoolManagement.csproj
      
    - name: Build
      run: dotnet build SchoolManagement/SchoolManagement.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish SchoolManagement/SchoolManagement.csproj --configuration Release --output publish --no-restore
      
    - name: Check Publish Output
      run: |
        if [ ! -d "publish" ]; then
          echo "Publish output directory not found!"
          exit 1
        fi
        echo "Publish output found in publish directory"
        
    - name: Clean FTP Directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /sms/
        dangerous-clean-slate: true
        log-level: verbose
        
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /sms/
        log-level: verbose 